# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=release
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),release)
  PokemonStadium_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := PokemonStadium

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

PokemonStadium:
ifneq (,$(PokemonStadium_config))
	@echo "==== Building PokemonStadium ($(PokemonStadium_config)) ===="
	@${MAKE} --no-print-directory -C . -f PokemonStadium.make config=$(PokemonStadium_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f PokemonStadium.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   PokemonStadium"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"